"""Category definitions and seed concepts for diverse idea generation.

CATEGORY_SEEDS is the static category data dictionary. The diversity
prompt templates (combinatoric, contrarian, persona) used to live here
too; they moved to engine/diversity_prompts.py to keep this module
focused on category data. Imports from the old location still work via
the re-exports at the bottom of this module.
"""

from project_forge.engine.diversity_prompts import (
    COMBINATORIC_TEMPLATES,
    CONTRARIAN_PROMPTS,
    PERSONA_SEEDS,
)
from project_forge.models import IdeaCategory

CATEGORY_SEEDS: dict[IdeaCategory, dict] = {
    IdeaCategory.SECURITY_TOOL: {
        "description": "Tools that fill gaps in the security toolchain",
        "seed_concepts": [
            "supply chain attack detection",
            "runtime memory forensics",
            "API key rotation automation",
            "zero-trust micro-segmentation",
            "firmware integrity verification",
            "secrets sprawl detection across repos",
            "lateral movement detection in containerized environments",
            "post-quantum cryptography migration tools",
            "container image provenance verification",
            "SBOM drift detection between builds",
            "cloud IAM permission creep analyzer",
            "TLS certificate misconfiguration scanner",
            "runtime dependency injection attack detector",
            "identity-based access revocation auditor",
            "cryptographic agility compliance scanner",
            "shadow IT discovery and risk assessor",
            "OAuth consent scope minimization advisor",
            "certificate transparency log abuse detector",
            "SSH key lifecycle governance tool",
            "binary composition analysis for open-source deps",
            "VPN split-tunneling policy enforcer",
            "API authentication scheme misconfiguration finder",
            "memory-safe rewrite migration tooling",
            "service account privilege escalation detector",
            "browser extension supply chain risk scanner",
        ],
        "domains_to_cross": [
            "healthcare",
            "IoT",
            "automotive",
            "fintech",
            "gaming",
            "aerospace",
            "retail",
            "defense",
            "education",
            "legal",
            "energy",
            "logistics",
            "smart city",
            "insurance",
            "telecommunications",
        ],
    },
    IdeaCategory.MARKET_GAP: {
        "description": "Products or services missing from the market",
        "seed_concepts": [
            "developer tool fatigue aggregator",
            "technical debt quantification platform",
            "open-source sustainability metrics",
            "cross-cloud cost anomaly detection",
            "infrastructure archaeology for legacy systems",
            "compliance-as-code marketplace",
            "developer onboarding time-to-first-commit optimizer",
            "SaaS feature usage dead code detector",
            "API deprecation impact predictor",
            "incident postmortem pattern miner",
            "vendor lock-in escape cost estimator",
            "configuration sprawl visualizer",
            "SaaS contract renewal risk predictor",
            "developer experience satisfaction tracker",
            "team knowledge bus factor analyzer",
            "on-call engineer burnout early warning system",
            "open-source library migration cost estimator",
            "monorepo sprawl growth visualizer",
            "cloud egress cost optimizer",
            "internal platform adoption analytics dashboard",
            "cross-team API compatibility tracker",
            "software bill of health dashboard",
        ],
        "domains_to_cross": [
            "education",
            "government",
            "nonprofit",
            "logistics",
            "agriculture",
            "media",
            "construction",
            "pharma",
            "healthcare",
            "startup ecosystem",
            "financial services",
            "retail",
            "gaming",
            "defense",
            "real estate",
        ],
    },
    IdeaCategory.VULNERABILITY_RESEARCH: {
        "description": "Novel vulnerability discovery and analysis approaches",
        "seed_concepts": [
            "LLM prompt injection fuzzer",
            "smart contract formal verification",
            "protocol-level timing attack detector",
            "browser extension permission abuse scanner",
            "CI/CD pipeline privilege escalation finder",
            "GraphQL introspection exploit kit",
            "WebAssembly sandbox escape detector",
            "DNS rebinding attack surface mapper",
            "OAuth token confusion attack detector",
            "kernel eBPF verifier bypass finder",
            "HTTP request smuggling variant scanner",
            "deserialization gadget chain discoverer",
            "AI model inference side-channel detector",
            "supply chain compromise in package registries",
            "JWT algorithm confusion attack scanner",
            "cloud metadata service abuse detector",
            "serverless function privilege escalation scanner",
            "insecure direct object reference mass scanner",
            "cross-tenant isolation test framework",
            "broken authentication chain analyzer",
            "misconfigured cloud storage bucket finder",
        ],
        "domains_to_cross": [
            "embedded systems",
            "satellites",
            "medical devices",
            "voting systems",
            "robotics",
            "SCADA",
            "autonomous vehicles",
            "smart homes",
            "payment systems",
            "authentication services",
            "CDN providers",
            "developer tools",
            "API gateways",
            "cloud functions",
            "industrial control systems",
        ],
    },
    IdeaCategory.AUTOMATION: {
        "description": "Workflow and process automation that saves real time",
        "seed_concepts": [
            "incident response runbook executor",
            "regulatory change impact assessor",
            "meeting-to-ticket pipeline",
            "cross-team dependency conflict resolver",
            "automated architecture decision records",
            "changelog-to-migration-guide generator",
            "stale documentation detector and updater",
            "test environment provisioning orchestrator",
            "release readiness gate evaluator",
            "on-call handoff context summarizer",
            "flaky test quarantine and triage bot",
            "infrastructure cost allocation tagger",
            "automated security questionnaire responder",
            "vendor onboarding workflow automator",
            "API contract evolution diff enforcer",
            "PR review checklist auto-populator",
            "sprint retrospective insight generator",
            "cloud resource tagging policy enforcer",
            "cross-repo dependency update coordinator",
            "knowledge base gap detection and fill bot",
            "SLA breach early warning automation",
        ],
        "domains_to_cross": [
            "legal",
            "real estate",
            "insurance",
            "manufacturing",
            "energy",
            "telecom",
            "hospitality",
            "aviation",
            "banking",
            "healthcare",
            "government",
            "logistics",
            "retail",
            "pharma",
            "education",
        ],
    },
    IdeaCategory.DEVOPS_TOOLING: {
        "description": "Developer experience and infrastructure tools",
        "seed_concepts": [
            "deployment rollback confidence scorer",
            "infrastructure drift detector with fix suggestions",
            "multi-cloud service mesh visualizer",
            "CI pipeline bottleneck profiler",
            "ephemeral environment cost optimizer",
            "feature flag lifecycle manager",
            "database migration risk assessor",
            "service dependency graph auto-documenter",
            "Dockerfile layer optimization advisor",
            "GitOps drift reconciliation dashboard",
            "secret rotation impact blast radius mapper",
            "canary deployment decision engine",
            "container registry compliance gatekeeper",
            "developer portal self-service catalog builder",
            "golden path template enforcer for new services",
            "pre-production environment config drift detector",
            "build cache efficiency optimizer",
            "on-call runbook freshness verifier",
            "cloud quota exhaustion early warning system",
            "multi-region failover readiness scorer",
            "platform engineering adoption metrics collector",
        ],
        "domains_to_cross": [
            "edge computing",
            "serverless",
            "bare metal",
            "hybrid cloud",
            "on-prem",
            "multi-tenant SaaS",
            "air-gapped networks",
            "GPU clusters",
            "regulated industries",
            "startup teams",
            "enterprise",
            "gaming infrastructure",
            "IoT fleet management",
            "ML infrastructure",
            "financial services",
        ],
    },
    IdeaCategory.PRIVACY: {
        "description": "Privacy-preserving technologies and tools",
        "seed_concepts": [
            "PII detection in unstructured data streams",
            "differential privacy budget tracker",
            "consent management for microservices",
            "data lineage tracker across distributed systems",
            "synthetic data generation with privacy guarantees",
            "browser fingerprinting resistance tester",
            "cross-border data flow compliance mapper",
            "privacy impact assessment automation",
            "data subject access request fulfillment engine",
            "cookie consent dark pattern detector",
            "federated learning privacy audit tool",
            "anonymization quality verifier",
            "re-identification risk scorer for datasets",
            "right-to-erasure workflow orchestrator",
            "shadow data store discovery tool",
            "third-party SDK data exfiltration detector",
            "privacy-preserving analytics pipeline builder",
            "data minimization policy enforcer",
            "cross-device identity linkage risk assessor",
            "privacy policy change impact notifier",
            "sensitive attribute inference attack detector",
        ],
        "domains_to_cross": [
            "children's data",
            "biometrics",
            "location tracking",
            "health records",
            "financial data",
            "employee monitoring",
            "social media",
            "genetic data",
            "education records",
            "insurance data",
            "criminal records",
            "immigration data",
            "mental health data",
            "IoT sensor data",
            "behavioral analytics",
        ],
    },
    IdeaCategory.COMPLIANCE: {
        "description": "Regulatory compliance automation and monitoring",
        "seed_concepts": [
            "SOC 2 evidence collection automation",
            "SBOM generation and vulnerability tracking",
            "access review automation with anomaly detection",
            "audit trail immutability verification",
            "policy-as-code enforcement engine",
            "third-party vendor risk continuous monitoring",
            "license compliance for transitive dependencies",
            "data retention policy enforcer",
            "control gap analysis between frameworks",
            "evidence chain-of-custody tracker",
            "regulatory horizon scanner for upcoming mandates",
            "segregation of duties conflict detector",
            "continuous compliance posture scoring",
            "automated pen test evidence collector",
            "board-level risk reporting automation",
            "supply chain due diligence tracker",
            "exception management and risk acceptance workflow",
            "compliance cost quantification tool",
            "multi-framework control overlap visualizer",
            "regulatory change notification automation",
            "automated questionnaire response generator",
        ],
        "domains_to_cross": [
            "HIPAA",
            "FedRAMP",
            "GDPR",
            "PCI-DSS",
            "CMMC",
            "SOX",
            "ISO 27001",
            "NIST CSF",
            "DORA",
            "CIS Controls",
            "SWIFT CSP",
            "NIS2",
            "CCPA",
            "TSA cybersecurity directives",
            "SEC cyber disclosure rules",
        ],
    },
    IdeaCategory.OBSERVABILITY: {
        "description": "Monitoring, logging, and tracing innovations",
        "seed_concepts": [
            "cost-aware log sampling engine",
            "trace-based testing framework",
            "anomaly detection for distributed traces",
            "SLO burn rate predictor",
            "customer-facing status page from internal metrics",
            "log-to-metric automatic converter",
            "observability data deduplication engine",
            "cross-service error correlation mapper",
            "alert fatigue scoring and prioritization",
            "distributed system topology auto-mapper",
            "latency budget allocation advisor",
            "cardinality explosion detector for metrics",
            "eBPF-based zero-instrumentation profiler",
            "dependency call graph drift detector",
            "multi-cluster log aggregation normalizer",
            "user journey tracing from frontend to database",
            "continuous profiling cost optimizer",
            "golden signal regression detector on deploys",
            "noise-aware alerting with context enrichment",
            "telemetry schema breaking change detector",
            "observability data governance and retention manager",
        ],
        "domains_to_cross": [
            "mobile apps",
            "CLI tools",
            "batch jobs",
            "real-time systems",
            "ML pipelines",
            "microservices",
            "event-driven systems",
            "data warehouses",
            "IoT devices",
            "edge computing",
            "gaming backends",
            "financial trading systems",
            "healthcare systems",
            "government platforms",
            "developer toolchains",
        ],
    },
    IdeaCategory.PQC_CRYPTOGRAPHY: {
        "description": "Post-quantum cryptography tools, migration, and security gap analysis",
        "seed_concepts": [
            "PQC CRL issuance with ML-DSA signatures — CRL size explosion mitigation",
            "hybrid certificate revocation (classical + PQC) management tools",
            "OCSP responder performance optimization for PQC signature verification",
            "CRL distribution point redesign for large PQC-signed CRLs",
            "delta CRL strategies for post-quantum certificate authorities",
            "ML-DSA (Dilithium) certificate chain validation tooling",
            "SLH-DSA (SPHINCS+) signature size impact on CRL bandwidth",
            "PQC certificate transparency log compatibility",
            "post-quantum TLS handshake performance profiler",
            "hybrid key encapsulation mechanism (KEM) migration planner",
            "FIPS 204 ML-DSA implementation conformance tester",
            "PQC algorithm agility framework for certificate issuance",
            "post-quantum OCSP stapling optimization",
            "CRL over QUIC transport for PQC-era bandwidth constraints",
            "PQC certificate lifecycle management platform",
            "quantum-safe timestamping service",
            "composite signature scheme compatibility tester",
            "PQC key backup and escrow migration tool",
            "classical-to-PQC crypto inventory migration planner",
            "PQC readiness assessment scanner for enterprise PKI",
            "quantum random number generator integration toolkit",
            "PQC signature size budget calculator for constrained devices",
        ],
        "domains_to_cross": [
            "PKI",
            "TLS",
            "code signing",
            "email security (S/MIME)",
            "IoT device certificates",
            "government/DoD",
            "document signing",
            "container image signing",
            "SSH key infrastructure",
            "VPN certificates",
            "smart card authentication",
            "DNSSEC",
            "blockchain/distributed ledger",
            "timestamping authorities",
            "automotive V2X certificates",
        ],
    },
    IdeaCategory.NIST_STANDARDS: {
        "description": "NIST compliance tooling, FIPS implementation, and standards automation",
        "seed_concepts": [
            "FIPS 203 (ML-KEM) compliance test suite generator",
            "FIPS 204 (ML-DSA) implementation validator",
            "FIPS 205 (SLH-DSA) performance benchmark suite",
            "NIST SP 800-208 compliance checker for stateful hash-based signatures",
            "NIST CAVP (Crypto Algorithm Validation Program) test automation",
            "NIST SP 800-57 key management lifecycle automation",
            "CMVP module validation evidence collector",
            "NIST SP 800-131A cryptographic transition compliance scanner",
            "NIST CSF 2.0 to technical controls mapper",
            "NIST SP 800-53 control inheritance automation for cloud",
            "FedRAMP continuous monitoring automation toolkit",
            "NIST 800-63 digital identity assurance level calculator",
            "FIPS 140-3 module boundary documentation generator",
            "NIST SP 800-171 self-assessment automation toolkit",
            "NIST AI RMF implementation workbench",
            "NIST SP 800-218 (SSDF) compliance tracker",
            "NIST SP 800-161 supply chain risk management scorer",
            "NIST Privacy Framework gap assessment tool",
            "NIST SP 800-30 risk assessment automation toolkit",
            "NIST SP 800-37 RMF authorization workflow engine",
            "NIST CSF profile comparison and gap analyzer",
        ],
        "domains_to_cross": [
            "cloud",
            "federal government",
            "healthcare",
            "financial services",
            "defense/DoD",
            "critical infrastructure",
            "automotive",
            "telecommunications",
            "education",
            "energy sector",
            "state and local government",
            "research institutions",
            "manufacturing",
            "transportation",
            "space systems",
        ],
    },
    IdeaCategory.RFC_SECURITY: {
        "description": "Tools built around IETF RFCs and security standards implementation",
        "seed_concepts": [
            "RFC compliance checker for TLS 1.3 implementations",
            "IETF LAMPS working group draft tracker and impact analyzer",
            "RFC 9629 KEM-in-CMS implementation and test toolkit",
            "ACME protocol (RFC 8555) PQC extension prototyping",
            "RFC 6960 OCSP protocol PQC signature performance analyzer",
            "RFC 5280 X.509 certificate profile validator for PQC algorithms",
            "IETF draft-to-implementation gap analyzer",
            "RFC security advisory correlator with CVE database",
            "TLS 1.3 (RFC 8446) post-quantum key exchange monitor",
            "RFC 9162 Certificate Transparency v2 PQC compatibility checker",
            "IETF CFRG algorithm recommendation tracker",
            "RFC interoperability test suite generator",
            "DANE (RFC 6698) TLSA record validator and deployer",
            "CAA (RFC 8659) policy enforcement auditor",
            "RFC 8615 well-known URI security metadata crawler",
            "IETF OAUTH 2.1 migration compliance checker",
            "RFC 9325 TLS recommendations enforcement tool",
            "PKIX path validation conformance test harness",
            "IETF working group implementer alert subscription",
            "RFC deprecation impact analysis for deployed systems",
            "IETF DMARC (RFC 7489) policy analyzer and enforcer",
        ],
        "domains_to_cross": [
            "web browsers",
            "email servers",
            "VPN",
            "CDN providers",
            "certificate authorities",
            "HSM vendors",
            "API gateways",
            "service meshes",
            "IoT protocols",
            "mobile applications",
            "payment terminals",
            "government portals",
            "healthcare interoperability",
            "financial messaging",
            "DNS resolvers",
        ],
    },
    IdeaCategory.CRYPTO_INFRASTRUCTURE: {
        "description": "Cryptographic infrastructure, PKI, certificate management, and key lifecycle tools",
        "seed_concepts": [
            "PKI health dashboard with revocation status monitoring",
            "certificate chain path-building optimization for PQC",
            "OCSP response caching strategy optimizer for high-traffic CAs",
            "cross-signed certificate migration planning tool",
            "HSM fleet management and PQC readiness assessor",
            "certificate pinning migration tool for PQC transition",
            "automated CA ceremony audit trail verifier",
            "crypto inventory scanner for certificates, keys, and algorithms",
            "certificate expiration prediction and auto-renewal orchestrator",
            "PKCS#11 provider compatibility matrix generator",
            "root store program compliance checker (Mozilla, Apple, Google)",
            "certificate misuse and abuse detection system",
            "ACME client interoperability test harness",
            "key ceremony workflow automation and evidence capture",
            "subordinate CA issuance policy compliance verifier",
            "certificate profile deviation alerting tool",
            "multi-CA trust anchor consolidation planner",
            "HSM partition utilization and capacity forecaster",
            "certificate churn rate analyzer for large PKI deployments",
            "private CA cost-per-certificate optimization advisor",
            "trust store poisoning detection tool",
        ],
        "domains_to_cross": [
            "cloud-native",
            "embedded/IoT",
            "automotive V2X",
            "telecom 5G",
            "smart grid",
            "banking",
            "satellite comms",
            "industrial control",
            "federal government",
            "healthcare interoperability",
            "DevSecOps pipelines",
            "zero-trust architectures",
            "service mesh",
            "multi-cloud environments",
            "air-gapped networks",
        ],
    },
    IdeaCategory.SELF_IMPROVEMENT: {
        "description": (
            "Self-improvement ideas for Project Forge itself — "
            "missing tests, CI gaps, UX enhancements, security hardening, and performance wins"
        ),
        "seed_concepts": [
            "automated test coverage enforcement for untested modules",
            "CI pipeline gap detection and remediation",
            "security hardening of API endpoints and input validation",
            "dashboard UX improvements and accessibility gaps",
            "database query performance profiling and indexing",
            "error handling gaps in async code paths",
            "missing rate limiting on generation endpoints",
            "idea deduplication algorithm improvements",
            "observability additions — structured logging, metrics, tracing",
            "dependency audit automation and CVE alerting",
            "scaffold quality validation and rollback safety",
            "self-hosted runner health monitoring",
        ],
        "domains_to_cross": [
            "test engineering",
            "DevSecOps",
            "developer experience",
            "reliability engineering",
            "performance engineering",
        ],
    },
}


# Re-exports for backward compat — these used to live here.
__all__ = ["CATEGORY_SEEDS", "COMBINATORIC_TEMPLATES", "CONTRARIAN_PROMPTS", "PERSONA_SEEDS"]
