"""Category definitions and seed concepts for diverse idea generation."""

from project_forge.models import IdeaCategory

CATEGORY_SEEDS: dict[IdeaCategory, dict] = {
    IdeaCategory.SECURITY_TOOL: {
        "description": "Tools that fill gaps in the security toolchain",
        "seed_concepts": [
            "supply chain attack detection",
            "runtime memory forensics",
            "API key rotation automation",
            "zero-trust micro-segmentation",
            "firmware integrity verification",
            "secrets sprawl detection across repos",
            "lateral movement detection in containerized environments",
            "post-quantum cryptography migration tools",
        ],
        "domains_to_cross": ["healthcare", "IoT", "automotive", "fintech", "gaming"],
    },
    IdeaCategory.MARKET_GAP: {
        "description": "Products or services missing from the market",
        "seed_concepts": [
            "developer tool fatigue aggregator",
            "technical debt quantification platform",
            "open-source sustainability metrics",
            "cross-cloud cost anomaly detection",
            "infrastructure archaeology for legacy systems",
            "compliance-as-code marketplace",
            "developer onboarding time-to-first-commit optimizer",
            "SaaS feature usage dead code detector",
        ],
        "domains_to_cross": ["education", "government", "nonprofit", "logistics", "agriculture"],
    },
    IdeaCategory.VULNERABILITY_RESEARCH: {
        "description": "Novel vulnerability discovery and analysis approaches",
        "seed_concepts": [
            "LLM prompt injection fuzzer",
            "smart contract formal verification",
            "protocol-level timing attack detector",
            "browser extension permission abuse scanner",
            "CI/CD pipeline privilege escalation finder",
            "GraphQL introspection exploit kit",
            "WebAssembly sandbox escape detector",
            "DNS rebinding attack surface mapper",
        ],
        "domains_to_cross": ["embedded systems", "satellites", "medical devices", "voting systems", "robotics"],
    },
    IdeaCategory.AUTOMATION: {
        "description": "Workflow and process automation that saves real time",
        "seed_concepts": [
            "incident response runbook executor",
            "regulatory change impact assessor",
            "meeting-to-ticket pipeline",
            "cross-team dependency conflict resolver",
            "automated architecture decision records",
            "changelog-to-migration-guide generator",
            "stale documentation detector and updater",
            "test environment provisioning orchestrator",
        ],
        "domains_to_cross": ["legal", "real estate", "insurance", "manufacturing", "energy"],
    },
    IdeaCategory.DEVOPS_TOOLING: {
        "description": "Developer experience and infrastructure tools",
        "seed_concepts": [
            "deployment rollback confidence scorer",
            "infrastructure drift detector with fix suggestions",
            "multi-cloud service mesh visualizer",
            "CI pipeline bottleneck profiler",
            "ephemeral environment cost optimizer",
            "feature flag lifecycle manager",
            "database migration risk assessor",
            "service dependency graph auto-documenter",
        ],
        "domains_to_cross": ["edge computing", "serverless", "bare metal", "hybrid cloud", "on-prem"],
    },
    IdeaCategory.PRIVACY: {
        "description": "Privacy-preserving technologies and tools",
        "seed_concepts": [
            "PII detection in unstructured data streams",
            "differential privacy budget tracker",
            "consent management for microservices",
            "data lineage tracker across distributed systems",
            "synthetic data generation with privacy guarantees",
            "browser fingerprinting resistance tester",
            "cross-border data flow compliance mapper",
            "privacy impact assessment automation",
        ],
        "domains_to_cross": ["children's data", "biometrics", "location tracking", "health records", "financial data"],
    },
    IdeaCategory.COMPLIANCE: {
        "description": "Regulatory compliance automation and monitoring",
        "seed_concepts": [
            "SOC 2 evidence collection automation",
            "SBOM generation and vulnerability tracking",
            "access review automation with anomaly detection",
            "audit trail immutability verification",
            "policy-as-code enforcement engine",
            "third-party vendor risk continuous monitoring",
            "license compliance for transitive dependencies",
            "data retention policy enforcer",
        ],
        "domains_to_cross": ["HIPAA", "FedRAMP", "GDPR", "PCI-DSS", "CMMC"],
    },
    IdeaCategory.OBSERVABILITY: {
        "description": "Monitoring, logging, and tracing innovations",
        "seed_concepts": [
            "cost-aware log sampling engine",
            "trace-based testing framework",
            "anomaly detection for distributed traces",
            "SLO burn rate predictor",
            "customer-facing status page from internal metrics",
            "log-to-metric automatic converter",
            "observability data deduplication engine",
            "cross-service error correlation mapper",
        ],
        "domains_to_cross": ["mobile apps", "CLI tools", "batch jobs", "real-time systems", "ML pipelines"],
    },
    IdeaCategory.PQC_CRYPTOGRAPHY: {
        "description": "Post-quantum cryptography tools, migration, and security gap analysis",
        "seed_concepts": [
            "PQC CRL issuance with ML-DSA signatures — CRL size explosion mitigation",
            "hybrid certificate revocation (classical + PQC) management tools",
            "OCSP responder performance optimization for PQC signature verification",
            "CRL distribution point redesign for large PQC-signed CRLs",
            "delta CRL strategies for post-quantum certificate authorities",
            "ML-DSA (Dilithium) certificate chain validation tooling",
            "SLH-DSA (SPHINCS+) signature size impact on CRL bandwidth",
            "PQC certificate transparency log compatibility",
            "post-quantum TLS handshake performance profiler",
            "hybrid key encapsulation mechanism (KEM) migration planner",
            "FIPS 204 ML-DSA implementation conformance tester",
            "PQC algorithm agility framework for certificate issuance",
            "post-quantum OCSP stapling optimization",
            "CRL over QUIC transport for PQC-era bandwidth constraints",
            "PQC certificate lifecycle management platform",
            "quantum-safe timestamping service",
        ],
        "domains_to_cross": [
            "PKI",
            "TLS",
            "code signing",
            "email security (S/MIME)",
            "IoT device certificates",
            "government/DoD",
        ],
    },
    IdeaCategory.NIST_STANDARDS: {
        "description": "NIST compliance tooling, FIPS implementation, and standards automation",
        "seed_concepts": [
            "FIPS 203 (ML-KEM) compliance test suite generator",
            "FIPS 204 (ML-DSA) implementation validator",
            "FIPS 205 (SLH-DSA) performance benchmark suite",
            "NIST SP 800-208 compliance checker for stateful hash-based signatures",
            "NIST CAVP (Crypto Algorithm Validation Program) test automation",
            "NIST SP 800-57 key management lifecycle automation",
            "CMVP module validation evidence collector",
            "NIST SP 800-131A cryptographic transition compliance scanner",
            "NIST CSF 2.0 to technical controls mapper",
            "NIST SP 800-53 control inheritance automation for cloud",
            "FedRAMP continuous monitoring automation toolkit",
            "NIST 800-63 digital identity assurance level calculator",
        ],
        "domains_to_cross": [
            "cloud",
            "federal government",
            "healthcare",
            "financial services",
            "defense/DoD",
            "critical infrastructure",
        ],
    },
    IdeaCategory.RFC_SECURITY: {
        "description": "Tools built around IETF RFCs and security standards implementation",
        "seed_concepts": [
            "RFC compliance checker for TLS 1.3 implementations",
            "IETF LAMPS working group draft tracker and impact analyzer",
            "RFC 9629 KEM-in-CMS implementation and test toolkit",
            "ACME protocol (RFC 8555) PQC extension prototyping",
            "RFC 6960 OCSP protocol PQC signature performance analyzer",
            "RFC 5280 X.509 certificate profile validator for PQC algorithms",
            "IETF draft-to-implementation gap analyzer",
            "RFC security advisory correlator with CVE database",
            "TLS 1.3 (RFC 8446) post-quantum key exchange monitor",
            "RFC 9162 Certificate Transparency v2 PQC compatibility checker",
            "IETF CFRG algorithm recommendation tracker",
            "RFC interoperability test suite generator",
        ],
        "domains_to_cross": [
            "web browsers",
            "email servers",
            "VPN",
            "CDN providers",
            "certificate authorities",
            "HSM vendors",
        ],
    },
    IdeaCategory.CRYPTO_INFRASTRUCTURE: {
        "description": "Cryptographic infrastructure, PKI, certificate management, and key lifecycle tools",
        "seed_concepts": [
            "PKI health dashboard with revocation status monitoring",
            "certificate chain path-building optimization for PQC",
            "OCSP response caching strategy optimizer for high-traffic CAs",
            "cross-signed certificate migration planning tool",
            "HSM fleet management and PQC readiness assessor",
            "certificate pinning migration tool for PQC transition",
            "automated CA ceremony audit trail verifier",
            "crypto inventory scanner — find all certificates, keys, and algorithms in your infrastructure",
            "certificate expiration prediction and auto-renewal orchestrator",
            "PKCS#11 provider compatibility matrix generator",
            "root store program compliance checker (Mozilla, Apple, Google)",
            "certificate misuse and abuse detection system",
        ],
        "domains_to_cross": ["cloud-native", "embedded/IoT", "automotive V2X", "telecom 5G", "smart grid", "banking"],
    },
    IdeaCategory.SELF_IMPROVEMENT: {
        "description": (
            "Self-improvement ideas for Project Forge itself — "
            "missing tests, CI gaps, UX enhancements, security hardening, and performance wins"
        ),
        "seed_concepts": [
            "automated test coverage enforcement for untested modules",
            "CI pipeline gap detection and remediation",
            "security hardening of API endpoints and input validation",
            "dashboard UX improvements and accessibility gaps",
            "database query performance profiling and indexing",
            "error handling gaps in async code paths",
            "missing rate limiting on generation endpoints",
            "idea deduplication algorithm improvements",
            "observability additions — structured logging, metrics, tracing",
            "dependency audit automation and CVE alerting",
            "scaffold quality validation and rollback safety",
            "self-hosted runner health monitoring",
        ],
        "domains_to_cross": [
            "test engineering",
            "DevSecOps",
            "developer experience",
            "reliability engineering",
            "performance engineering",
        ],
    },
}

COMBINATORIC_TEMPLATES = [
    "What if {concept_a} was applied to {domain_b}?",
    "What tool would you need if {concept_a} and {concept_b} had to work together?",
    "What's the opposite of {concept_a} -- and would building that be valuable?",
    "If {domain_a} had the same tooling maturity as {domain_b}, what would exist that doesn't today?",
    "What breaks first when {concept_a} scales to 10x its current usage?",
]

CONTRARIAN_PROMPTS = [
    "What security problem does everyone ignore because they think it's already solved?",
    "What developer tool is everyone building wrong because they copied the first implementation?",
    "What compliance requirement is actually an opportunity disguised as a burden?",
    "What monitoring gap only becomes visible during an incident -- but could be caught proactively?",
    "What problem is getting worse faster than the current solutions can keep up with?",
    "What would a startup build if they had zero legacy constraints but deep domain expertise?",
    "What tool do teams build internally over and over because no good open-source version exists?",
    "What's the 'spreadsheet that should be a product' in your domain?",
]
