"""Category definitions and seed concepts for diverse idea generation."""

from project_forge.models import IdeaCategory

CATEGORY_SEEDS: dict[IdeaCategory, dict] = {
    IdeaCategory.SECURITY_TOOL: {
        "description": "Tools that fill gaps in the security toolchain",
        "seed_concepts": [
            "supply chain attack detection",
            "runtime memory forensics",
            "API key rotation automation",
            "zero-trust micro-segmentation",
            "firmware integrity verification",
            "secrets sprawl detection across repos",
            "lateral movement detection in containerized environments",
            "post-quantum cryptography migration tools",
            "container image provenance verification",
            "SBOM drift detection between builds",
            "cloud IAM permission creep analyzer",
            "TLS certificate misconfiguration scanner",
            "runtime dependency injection attack detector",
            "identity-based access revocation auditor",
            "cryptographic agility compliance scanner",
            "shadow IT discovery and risk assessor",
            "OAuth consent scope minimization advisor",
            "certificate transparency log abuse detector",
            "SSH key lifecycle governance tool",
            "binary composition analysis for open-source deps",
            "VPN split-tunneling policy enforcer",
            "API authentication scheme misconfiguration finder",
            "memory-safe rewrite migration tooling",
            "service account privilege escalation detector",
            "browser extension supply chain risk scanner",
        ],
        "domains_to_cross": [
            "healthcare",
            "IoT",
            "automotive",
            "fintech",
            "gaming",
            "aerospace",
            "retail",
            "defense",
            "education",
            "legal",
            "energy",
            "logistics",
            "smart city",
            "insurance",
            "telecommunications",
        ],
    },
    IdeaCategory.MARKET_GAP: {
        "description": "Products or services missing from the market",
        "seed_concepts": [
            "developer tool fatigue aggregator",
            "technical debt quantification platform",
            "open-source sustainability metrics",
            "cross-cloud cost anomaly detection",
            "infrastructure archaeology for legacy systems",
            "compliance-as-code marketplace",
            "developer onboarding time-to-first-commit optimizer",
            "SaaS feature usage dead code detector",
            "API deprecation impact predictor",
            "incident postmortem pattern miner",
            "vendor lock-in escape cost estimator",
            "configuration sprawl visualizer",
            "SaaS contract renewal risk predictor",
            "developer experience satisfaction tracker",
            "team knowledge bus factor analyzer",
            "on-call engineer burnout early warning system",
            "open-source library migration cost estimator",
            "monorepo sprawl growth visualizer",
            "cloud egress cost optimizer",
            "internal platform adoption analytics dashboard",
            "cross-team API compatibility tracker",
            "software bill of health dashboard",
        ],
        "domains_to_cross": [
            "education",
            "government",
            "nonprofit",
            "logistics",
            "agriculture",
            "media",
            "construction",
            "pharma",
            "healthcare",
            "startup ecosystem",
            "financial services",
            "retail",
            "gaming",
            "defense",
            "real estate",
        ],
    },
    IdeaCategory.VULNERABILITY_RESEARCH: {
        "description": "Novel vulnerability discovery and analysis approaches",
        "seed_concepts": [
            "LLM prompt injection fuzzer",
            "smart contract formal verification",
            "protocol-level timing attack detector",
            "browser extension permission abuse scanner",
            "CI/CD pipeline privilege escalation finder",
            "GraphQL introspection exploit kit",
            "WebAssembly sandbox escape detector",
            "DNS rebinding attack surface mapper",
            "OAuth token confusion attack detector",
            "kernel eBPF verifier bypass finder",
            "HTTP request smuggling variant scanner",
            "deserialization gadget chain discoverer",
            "AI model inference side-channel detector",
            "supply chain compromise in package registries",
            "JWT algorithm confusion attack scanner",
            "cloud metadata service abuse detector",
            "serverless function privilege escalation scanner",
            "insecure direct object reference mass scanner",
            "cross-tenant isolation test framework",
            "broken authentication chain analyzer",
            "misconfigured cloud storage bucket finder",
        ],
        "domains_to_cross": [
            "embedded systems",
            "satellites",
            "medical devices",
            "voting systems",
            "robotics",
            "SCADA",
            "autonomous vehicles",
            "smart homes",
            "payment systems",
            "authentication services",
            "CDN providers",
            "developer tools",
            "API gateways",
            "cloud functions",
            "industrial control systems",
        ],
    },
    IdeaCategory.AUTOMATION: {
        "description": "Workflow and process automation that saves real time",
        "seed_concepts": [
            "incident response runbook executor",
            "regulatory change impact assessor",
            "meeting-to-ticket pipeline",
            "cross-team dependency conflict resolver",
            "automated architecture decision records",
            "changelog-to-migration-guide generator",
            "stale documentation detector and updater",
            "test environment provisioning orchestrator",
            "release readiness gate evaluator",
            "on-call handoff context summarizer",
            "flaky test quarantine and triage bot",
            "infrastructure cost allocation tagger",
            "automated security questionnaire responder",
            "vendor onboarding workflow automator",
            "API contract evolution diff enforcer",
            "PR review checklist auto-populator",
            "sprint retrospective insight generator",
            "cloud resource tagging policy enforcer",
            "cross-repo dependency update coordinator",
            "knowledge base gap detection and fill bot",
            "SLA breach early warning automation",
        ],
        "domains_to_cross": [
            "legal",
            "real estate",
            "insurance",
            "manufacturing",
            "energy",
            "telecom",
            "hospitality",
            "aviation",
            "banking",
            "healthcare",
            "government",
            "logistics",
            "retail",
            "pharma",
            "education",
        ],
    },
    IdeaCategory.DEVOPS_TOOLING: {
        "description": "Developer experience and infrastructure tools",
        "seed_concepts": [
            "deployment rollback confidence scorer",
            "infrastructure drift detector with fix suggestions",
            "multi-cloud service mesh visualizer",
            "CI pipeline bottleneck profiler",
            "ephemeral environment cost optimizer",
            "feature flag lifecycle manager",
            "database migration risk assessor",
            "service dependency graph auto-documenter",
            "Dockerfile layer optimization advisor",
            "GitOps drift reconciliation dashboard",
            "secret rotation impact blast radius mapper",
            "canary deployment decision engine",
            "container registry compliance gatekeeper",
            "developer portal self-service catalog builder",
            "golden path template enforcer for new services",
            "pre-production environment config drift detector",
            "build cache efficiency optimizer",
            "on-call runbook freshness verifier",
            "cloud quota exhaustion early warning system",
            "multi-region failover readiness scorer",
            "platform engineering adoption metrics collector",
        ],
        "domains_to_cross": [
            "edge computing",
            "serverless",
            "bare metal",
            "hybrid cloud",
            "on-prem",
            "multi-tenant SaaS",
            "air-gapped networks",
            "GPU clusters",
            "regulated industries",
            "startup teams",
            "enterprise",
            "gaming infrastructure",
            "IoT fleet management",
            "ML infrastructure",
            "financial services",
        ],
    },
    IdeaCategory.PRIVACY: {
        "description": "Privacy-preserving technologies and tools",
        "seed_concepts": [
            "PII detection in unstructured data streams",
            "differential privacy budget tracker",
            "consent management for microservices",
            "data lineage tracker across distributed systems",
            "synthetic data generation with privacy guarantees",
            "browser fingerprinting resistance tester",
            "cross-border data flow compliance mapper",
            "privacy impact assessment automation",
            "data subject access request fulfillment engine",
            "cookie consent dark pattern detector",
            "federated learning privacy audit tool",
            "anonymization quality verifier",
            "re-identification risk scorer for datasets",
            "right-to-erasure workflow orchestrator",
            "shadow data store discovery tool",
            "third-party SDK data exfiltration detector",
            "privacy-preserving analytics pipeline builder",
            "data minimization policy enforcer",
            "cross-device identity linkage risk assessor",
            "privacy policy change impact notifier",
            "sensitive attribute inference attack detector",
        ],
        "domains_to_cross": [
            "children's data",
            "biometrics",
            "location tracking",
            "health records",
            "financial data",
            "employee monitoring",
            "social media",
            "genetic data",
            "education records",
            "insurance data",
            "criminal records",
            "immigration data",
            "mental health data",
            "IoT sensor data",
            "behavioral analytics",
        ],
    },
    IdeaCategory.COMPLIANCE: {
        "description": "Regulatory compliance automation and monitoring",
        "seed_concepts": [
            "SOC 2 evidence collection automation",
            "SBOM generation and vulnerability tracking",
            "access review automation with anomaly detection",
            "audit trail immutability verification",
            "policy-as-code enforcement engine",
            "third-party vendor risk continuous monitoring",
            "license compliance for transitive dependencies",
            "data retention policy enforcer",
            "control gap analysis between frameworks",
            "evidence chain-of-custody tracker",
            "regulatory horizon scanner for upcoming mandates",
            "segregation of duties conflict detector",
            "continuous compliance posture scoring",
            "automated pen test evidence collector",
            "board-level risk reporting automation",
            "supply chain due diligence tracker",
            "exception management and risk acceptance workflow",
            "compliance cost quantification tool",
            "multi-framework control overlap visualizer",
            "regulatory change notification automation",
            "automated questionnaire response generator",
        ],
        "domains_to_cross": [
            "HIPAA",
            "FedRAMP",
            "GDPR",
            "PCI-DSS",
            "CMMC",
            "SOX",
            "ISO 27001",
            "NIST CSF",
            "DORA",
            "CIS Controls",
            "SWIFT CSP",
            "NIS2",
            "CCPA",
            "TSA cybersecurity directives",
            "SEC cyber disclosure rules",
        ],
    },
    IdeaCategory.OBSERVABILITY: {
        "description": "Monitoring, logging, and tracing innovations",
        "seed_concepts": [
            "cost-aware log sampling engine",
            "trace-based testing framework",
            "anomaly detection for distributed traces",
            "SLO burn rate predictor",
            "customer-facing status page from internal metrics",
            "log-to-metric automatic converter",
            "observability data deduplication engine",
            "cross-service error correlation mapper",
            "alert fatigue scoring and prioritization",
            "distributed system topology auto-mapper",
            "latency budget allocation advisor",
            "cardinality explosion detector for metrics",
            "eBPF-based zero-instrumentation profiler",
            "dependency call graph drift detector",
            "multi-cluster log aggregation normalizer",
            "user journey tracing from frontend to database",
            "continuous profiling cost optimizer",
            "golden signal regression detector on deploys",
            "noise-aware alerting with context enrichment",
            "telemetry schema breaking change detector",
            "observability data governance and retention manager",
        ],
        "domains_to_cross": [
            "mobile apps",
            "CLI tools",
            "batch jobs",
            "real-time systems",
            "ML pipelines",
            "microservices",
            "event-driven systems",
            "data warehouses",
            "IoT devices",
            "edge computing",
            "gaming backends",
            "financial trading systems",
            "healthcare systems",
            "government platforms",
            "developer toolchains",
        ],
    },
    IdeaCategory.PQC_CRYPTOGRAPHY: {
        "description": "Post-quantum cryptography tools, migration, and security gap analysis",
        "seed_concepts": [
            "PQC CRL issuance with ML-DSA signatures — CRL size explosion mitigation",
            "hybrid certificate revocation (classical + PQC) management tools",
            "OCSP responder performance optimization for PQC signature verification",
            "CRL distribution point redesign for large PQC-signed CRLs",
            "delta CRL strategies for post-quantum certificate authorities",
            "ML-DSA (Dilithium) certificate chain validation tooling",
            "SLH-DSA (SPHINCS+) signature size impact on CRL bandwidth",
            "PQC certificate transparency log compatibility",
            "post-quantum TLS handshake performance profiler",
            "hybrid key encapsulation mechanism (KEM) migration planner",
            "FIPS 204 ML-DSA implementation conformance tester",
            "PQC algorithm agility framework for certificate issuance",
            "post-quantum OCSP stapling optimization",
            "CRL over QUIC transport for PQC-era bandwidth constraints",
            "PQC certificate lifecycle management platform",
            "quantum-safe timestamping service",
            "composite signature scheme compatibility tester",
            "PQC key backup and escrow migration tool",
            "classical-to-PQC crypto inventory migration planner",
            "PQC readiness assessment scanner for enterprise PKI",
            "quantum random number generator integration toolkit",
            "PQC signature size budget calculator for constrained devices",
        ],
        "domains_to_cross": [
            "PKI",
            "TLS",
            "code signing",
            "email security (S/MIME)",
            "IoT device certificates",
            "government/DoD",
            "document signing",
            "container image signing",
            "SSH key infrastructure",
            "VPN certificates",
            "smart card authentication",
            "DNSSEC",
            "blockchain/distributed ledger",
            "timestamping authorities",
            "automotive V2X certificates",
        ],
    },
    IdeaCategory.NIST_STANDARDS: {
        "description": "NIST compliance tooling, FIPS implementation, and standards automation",
        "seed_concepts": [
            "FIPS 203 (ML-KEM) compliance test suite generator",
            "FIPS 204 (ML-DSA) implementation validator",
            "FIPS 205 (SLH-DSA) performance benchmark suite",
            "NIST SP 800-208 compliance checker for stateful hash-based signatures",
            "NIST CAVP (Crypto Algorithm Validation Program) test automation",
            "NIST SP 800-57 key management lifecycle automation",
            "CMVP module validation evidence collector",
            "NIST SP 800-131A cryptographic transition compliance scanner",
            "NIST CSF 2.0 to technical controls mapper",
            "NIST SP 800-53 control inheritance automation for cloud",
            "FedRAMP continuous monitoring automation toolkit",
            "NIST 800-63 digital identity assurance level calculator",
            "FIPS 140-3 module boundary documentation generator",
            "NIST SP 800-171 self-assessment automation toolkit",
            "NIST AI RMF implementation workbench",
            "NIST SP 800-218 (SSDF) compliance tracker",
            "NIST SP 800-161 supply chain risk management scorer",
            "NIST Privacy Framework gap assessment tool",
            "NIST SP 800-30 risk assessment automation toolkit",
            "NIST SP 800-37 RMF authorization workflow engine",
            "NIST CSF profile comparison and gap analyzer",
        ],
        "domains_to_cross": [
            "cloud",
            "federal government",
            "healthcare",
            "financial services",
            "defense/DoD",
            "critical infrastructure",
            "automotive",
            "telecommunications",
            "education",
            "energy sector",
            "state and local government",
            "research institutions",
            "manufacturing",
            "transportation",
            "space systems",
        ],
    },
    IdeaCategory.RFC_SECURITY: {
        "description": "Tools built around IETF RFCs and security standards implementation",
        "seed_concepts": [
            "RFC compliance checker for TLS 1.3 implementations",
            "IETF LAMPS working group draft tracker and impact analyzer",
            "RFC 9629 KEM-in-CMS implementation and test toolkit",
            "ACME protocol (RFC 8555) PQC extension prototyping",
            "RFC 6960 OCSP protocol PQC signature performance analyzer",
            "RFC 5280 X.509 certificate profile validator for PQC algorithms",
            "IETF draft-to-implementation gap analyzer",
            "RFC security advisory correlator with CVE database",
            "TLS 1.3 (RFC 8446) post-quantum key exchange monitor",
            "RFC 9162 Certificate Transparency v2 PQC compatibility checker",
            "IETF CFRG algorithm recommendation tracker",
            "RFC interoperability test suite generator",
            "DANE (RFC 6698) TLSA record validator and deployer",
            "CAA (RFC 8659) policy enforcement auditor",
            "RFC 8615 well-known URI security metadata crawler",
            "IETF OAUTH 2.1 migration compliance checker",
            "RFC 9325 TLS recommendations enforcement tool",
            "PKIX path validation conformance test harness",
            "IETF working group implementer alert subscription",
            "RFC deprecation impact analysis for deployed systems",
            "IETF DMARC (RFC 7489) policy analyzer and enforcer",
        ],
        "domains_to_cross": [
            "web browsers",
            "email servers",
            "VPN",
            "CDN providers",
            "certificate authorities",
            "HSM vendors",
            "API gateways",
            "service meshes",
            "IoT protocols",
            "mobile applications",
            "payment terminals",
            "government portals",
            "healthcare interoperability",
            "financial messaging",
            "DNS resolvers",
        ],
    },
    IdeaCategory.CRYPTO_INFRASTRUCTURE: {
        "description": "Cryptographic infrastructure, PKI, certificate management, and key lifecycle tools",
        "seed_concepts": [
            "PKI health dashboard with revocation status monitoring",
            "certificate chain path-building optimization for PQC",
            "OCSP response caching strategy optimizer for high-traffic CAs",
            "cross-signed certificate migration planning tool",
            "HSM fleet management and PQC readiness assessor",
            "certificate pinning migration tool for PQC transition",
            "automated CA ceremony audit trail verifier",
            "crypto inventory scanner for certificates, keys, and algorithms",
            "certificate expiration prediction and auto-renewal orchestrator",
            "PKCS#11 provider compatibility matrix generator",
            "root store program compliance checker (Mozilla, Apple, Google)",
            "certificate misuse and abuse detection system",
            "ACME client interoperability test harness",
            "key ceremony workflow automation and evidence capture",
            "subordinate CA issuance policy compliance verifier",
            "certificate profile deviation alerting tool",
            "multi-CA trust anchor consolidation planner",
            "HSM partition utilization and capacity forecaster",
            "certificate churn rate analyzer for large PKI deployments",
            "private CA cost-per-certificate optimization advisor",
            "trust store poisoning detection tool",
        ],
        "domains_to_cross": [
            "cloud-native",
            "embedded/IoT",
            "automotive V2X",
            "telecom 5G",
            "smart grid",
            "banking",
            "satellite comms",
            "industrial control",
            "federal government",
            "healthcare interoperability",
            "DevSecOps pipelines",
            "zero-trust architectures",
            "service mesh",
            "multi-cloud environments",
            "air-gapped networks",
        ],
    },
    IdeaCategory.SELF_IMPROVEMENT: {
        "description": (
            "Self-improvement ideas for Project Forge itself — "
            "missing tests, CI gaps, UX enhancements, security hardening, and performance wins"
        ),
        "seed_concepts": [
            "automated test coverage enforcement for untested modules",
            "CI pipeline gap detection and remediation",
            "security hardening of API endpoints and input validation",
            "dashboard UX improvements and accessibility gaps",
            "database query performance profiling and indexing",
            "error handling gaps in async code paths",
            "missing rate limiting on generation endpoints",
            "idea deduplication algorithm improvements",
            "observability additions — structured logging, metrics, tracing",
            "dependency audit automation and CVE alerting",
            "scaffold quality validation and rollback safety",
            "self-hosted runner health monitoring",
        ],
        "domains_to_cross": [
            "test engineering",
            "DevSecOps",
            "developer experience",
            "reliability engineering",
            "performance engineering",
        ],
    },
}

COMBINATORIC_TEMPLATES = [
    "What if {concept_a} was applied to {domain_b}?",
    "What tool would you need if {concept_a} and {concept_b} had to work together?",
    "What's the opposite of {concept_a} -- and would building that be valuable?",
    "If {domain_a} had the same tooling maturity as {domain_b}, what would exist that doesn't today?",
    "What breaks first when {concept_a} scales to 10x its current usage?",
]

CONTRARIAN_PROMPTS = [
    "What security problem does everyone ignore because they think it's already solved?",
    "What developer tool is everyone building wrong because they copied the first implementation?",
    "What compliance requirement is actually an opportunity disguised as a burden?",
    "What monitoring gap only becomes visible during an incident -- but could be caught proactively?",
    "What problem is getting worse faster than the current solutions can keep up with?",
    "What would a startup build if they had zero legacy constraints but deep domain expertise?",
    "What tool do teams build internally over and over because no good open-source version exists?",
    "What's the 'spreadsheet that should be a product' in your domain?",
]

# User persona seeds — each gives Claude a concrete human POV to generate from.
# The goal is to ground ideas in real pain, not abstract concept recombination.
PERSONA_SEEDS: list[dict] = [
    {
        "role": "CISO at a regional bank",
        "pain": "8-person security team, two audits per year, regulators who don't understand cloud. "
                "Any new tool must justify itself in a board slide.",
    },
    {
        "role": "PKI architect at a Fortune 500 migrating off a 15-year-old CA",
        "pain": "Thousands of certificates issued by an EOL CA, no inventory, half the cert owners "
                "have left the company. The board just approved PQC transition budget.",
    },
    {
        "role": "DevSecOps lead at a Series B startup with 18 engineers",
        "pain": "Moving fast, FedRAMP moderate in 6 months, no dedicated security team. "
                "Needs automation that works without a security hire.",
    },
    {
        "role": "Federal contractor under CMMC Level 2",
        "pain": "Contractually required to show continuous compliance evidence. "
                "Manual evidence collection is eating two weeks per quarter.",
    },
    {
        "role": "Red team lead at an MSSP",
        "pain": "Runs 40+ engagements a year across wildly different environments. "
                "Needs tooling that scales across clients without custom setup per engagement.",
    },
    {
        "role": "Embedded systems engineer at an automotive OEM",
        "pain": "ECU firmware must satisfy ISO 21434, V2X requires PQC-ready certs by 2027. "
                "Crypto libraries that work on 64KB RAM devices are almost nonexistent.",
    },
    {
        "role": "Open-source maintainer of a widely-used crypto library",
        "pain": "Constantly asked 'are you PQC ready?' with no good answer. "
                "Test coverage for algorithm edge cases is near zero. Users are production-deploying untested paths.",
    },
    {
        "role": "Network security engineer at a Tier-1 telecom",
        "pain": "5G core relies on TLS everywhere, certificate expiry causes P1 outages twice a year. "
                "HSM fleet spans 3 data centers and nobody has a full inventory.",
    },
    {
        "role": "Platform engineer at a cloud-native SaaS scaling from 10 to 500 services",
        "pain": "Service mesh cert rotation is manual, secrets are duplicated across 12 Kubernetes namespaces, "
                "and the on-call runbook hasn't been updated in 18 months.",
    },
    {
        "role": "Security researcher at an academic lab studying protocol attacks",
        "pain": "Needs reproducible environments to test TLS downgrade and side-channel attacks. "
                "Setting up a controlled PKI for experiments takes a week each time.",
    },
    {
        "role": "CTO at a healthcare SaaS startup",
        "pain": "HIPAA BAA with every customer, PHI in motion needs encryption audit trail, "
                "and the board just got spooked by a competitor's breach announcement.",
    },
    {
        "role": "IAM engineer at a global financial institution",
        "pain": "Certificate-based authentication for 80,000 employees, half still on smart cards. "
                "Every PQC upgrade requires touching every identity provider in the estate.",
    },
    {
        "role": "Vulnerability researcher doing independent CVE work",
        "pain": "Needs to quickly stand up test harnesses for protocol implementations to confirm "
                "whether a suspected bug is exploitable. Existing tooling assumes you know the target stack.",
    },
    {
        "role": "GRC analyst at a mid-market insurance company",
        "pain": "Maps controls manually across NIST CSF, SOC 2, and state insurance regs. "
                "A single framework change means weeks of spreadsheet rework.",
    },
    {
        "role": "Cloud security architect at a hyperscaler-adjacent ISV",
        "pain": "Customers demand FIPS-validated crypto in multi-tenant environments. "
                "Key isolation between tenants is a compliance requirement, not a nice-to-have.",
    },
]
